package madang.shared.ui

/** 가운데 열 탭과 탭 서랍 문구. */
data class TabStrings(
    val pageTab: String,
    val closeTab: String,
    val toBlock: (String) -> String,
    val showDrawer: String,
    val hideDrawer: String,
    val preview: String,
    val source: String,
    val table: String,
    val file: String,
    val createdBy: String,
    val format: String,
    val lines: (Int) -> String,
    val loading: String,
    val emptyContent: String,
    val runRequest: String,
    val inputParts: String,
    val inputTotal: String,
    val usage: String,
    val usageInput: String,
    val usageCached: String,
    val usageOutput: String,
    val changedFiles: String,
    val none: String,
    val eventLog: String,
    val noEvents: String
)

val KoreanTabStrings = TabStrings(
    pageTab = "페이지",
    closeTab = "탭 닫기",
    toBlock = { "${it}에게" },
    showDrawer = "패널 펼치기",
    hideDrawer = "패널 접기",
    preview = "미리보기",
    source = "원본",
    table = "표",
    file = "파일",
    createdBy = "만든 곳",
    format = "형식",
    lines = { "${it}줄" },
    loading = "불러오는 중",
    emptyContent = "내용이 없습니다",
    runRequest = "이 run을 일으킨 요청과 결과",
    inputParts = "입력 구성",
    inputTotal = "합계",
    usage = "사용량",
    usageInput = "입력",
    usageCached = "캐시",
    usageOutput = "출력",
    changedFiles = "바뀐 파일",
    none = "없음",
    eventLog = "이벤트 로그",
    noEvents = "이벤트가 없습니다"
)

val EnglishTabStrings = TabStrings(
    pageTab = "Page",
    closeTab = "Close tab",
    toBlock = { "To $it" },
    showDrawer = "Show panel",
    hideDrawer = "Hide panel",
    preview = "Preview",
    source = "Source",
    table = "Table",
    file = "File",
    createdBy = "Created by",
    format = "Format",
    lines = { "$it lines" },
    loading = "Loading",
    emptyContent = "No content",
    runRequest = "Request and result of this run",
    inputParts = "Input",
    inputTotal = "Total",
    usage = "Usage",
    usageInput = "Input",
    usageCached = "Cached",
    usageOutput = "Output",
    changedFiles = "Changed files",
    none = "None",
    eventLog = "Event log",
    noEvents = "No events"
)
